# docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: airline_booking
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: Str0ngP@ssw0rd
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/booking-frontend
    ports:
      - "3000:80"

volumes:
  db_data:
